name: RSS to Telegram Bot

on:
  schedule:
    - cron: '0 */1 * * *' # Запускать каждые 1 час
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python main.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}

      - name: Commit and push if processed_posts.txt changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add processed_posts.txt
          git diff --staged --quiet || git commit -m "Update processed posts list"
          git push
        if: success()
